const users = [
    { name: 'kadji', age: 18 },
    { name: 'alan', age: 41 },
    { name: 'gaetan',  age: 30 },
    { name: 'charles',  age: 55 },
    { name: 'clint',  age: 50 },
    { name: 'rash',   age: 56 },
    { name: 'joshua',  age: 47 },
    { name: 'emmanual', age: 48 },
    { name: 'alaric',   age: 60 },
    { name: 'christ',age: 50 },
    { name: 'nathaneal',age: 24 },
    { name: 'ange', age: 29 },
    { name: 'nehal', age: 53 },
    { name: 'nicole',  age: 43 },
    { name: 'jessica', age: 32 },
    { name: 'john',  age: 20},
    { name: ' jones',age: 17 },
    { name: 'johnny',age: 34 },
    { name: 'pryan',age: 26 },
    { name: 'cathy', age: 59 },
    { name: 'paul',age: 15 },
]